In [1]:
import numpy as np

url = "https://drive.google.com/uc?export=download&id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK"
data = np.loadtxt(url)
print(data)


[ 7. 10.  5. ...  5.  9. 10.]


In [2]:
data

array([ 7., 10.,  5., ...,  5.,  9., 10.])

Question 1: What NumPy technique is used to filter scores where respondents are detractors (score≤6)?

image.png

In [3]:
data

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [4]:
data<=6

array([False, False,  True, ...,  True, False, False])

In [5]:
data[data<=6]

array([5., 4., 4., 5., 1., 5., 5., 1., 4., 5., 4., 4., 4., 5., 1., 4., 1.,
       4., 1., 5., 5., 1., 1., 4., 1., 5., 4., 1., 1., 4., 1., 5., 1., 4.,
       4., 1., 1., 1., 1., 1., 1., 1., 4., 1., 1., 5., 5., 5., 4., 4., 1.,
       4., 1., 4., 1., 5., 1., 1., 5., 4., 4., 4., 4., 1., 4., 5., 4., 4.,
       1., 1., 5., 5., 1., 5., 1., 5., 5., 4., 5., 4., 1., 1., 1., 1., 4.,
       1., 4., 4., 5., 4., 1., 1., 1., 1., 5., 4., 5., 5., 4., 1., 5., 1.,
       4., 4., 1., 1., 1., 4., 4., 5., 5., 4., 5., 5., 5., 1., 4., 1., 5.,
       5., 1., 5., 1., 1., 5., 5., 4., 4., 1., 4., 4., 4., 1., 1., 4., 4.,
       4., 5., 5., 1., 1., 4., 1., 4., 1., 4., 1., 4., 1., 4., 1., 5., 4.,
       4., 5., 1., 4., 5., 5., 5., 1., 5., 4., 1., 1., 5., 5., 5., 4., 5.,
       4., 4., 1., 4., 4., 4., 4., 5., 1., 5., 5., 1., 4., 4., 5., 1., 1.,
       4., 5., 5., 5., 1., 4., 5., 5., 4., 1., 5., 5., 5., 1., 1., 5., 5.,
       1., 1., 1., 4., 5., 5., 4., 4., 4., 5., 1., 4., 1., 4., 5., 4., 5.,
       5., 1., 5., 1., 5.

In [7]:
data[data<=6].shape[0]

332

In [9]:
detractors = data[data <= 6]
# Number of detractors -
num_detractors = len(detractors)
num_detractors

332

Question 2: Which of the following correctly calculates the percentage of Promoters (where score≥9) from the NumPy array score?

In [13]:
promoters = data[data >= 9]
# Number of detractors -
num_promoters = len(promoters)
num_promoters

609

In [14]:
len(data)

1167

In [15]:
total = len(data)

In [16]:
percentage_promoters = (num_promoters/total) * 100
percentage_promoters

52.185089974293064

Question 3: What does this line of code calculate?
NPS = percentage_promoters - percentage_detractors

A. Number of respondents who are promoters.
B. Total percentage of neutral respondents.
C. Net Promoter Score (NPS).
D. Percentage of detractors only.

In [19]:
percentage_promoters

52.185089974293064

In [20]:
percentage_detractors = (num_detractors/total) * 100
percentage_detractors

28.449014567266495

In [21]:
nps = percentage_promoters - percentage_detractors
nps

23.73607540702657

# Use Case: Fitness data analysis


image.png

In [24]:
data = np.loadtxt("fit.txt",dtype = "str")
print(data)


[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']
 ['11-10-2017' '4545' 'Sad' '149' '6' 'Inactive']
 ['12-10-2017' '4340' 'Sad' '140' '6' 'Inactive']
 ['13-10-2017' '1230' 'Sad' '38' '7' 'Inactive']
 ['14-10-2017' '61' 'Sad' '1' '5' 'Inactive']
 ['15-10-2017' '1258' 'Sad' '40' '6' 'Inactive']
 ['16-10-2017' '3148' 'Sad' '101' '8' 'Inactive']
 ['17-10-2017' '4687' 'Sad' '152' '5' 'Inactive']
 ['18-10-2017' '4732' 'Happy' '150' '6' 'Active']
 ['19-10-2017' '3519' 'Sad' '113' '7' 'Inactive']
 ['20-10-2017' '1580' 'Sad' '49' '5' 'Inactive']
 ['21-10-2017' '2822' 'Sad' '86' '6' 'Inactive']
 ['22-10-2017' '181' 'Sad' '6' '8' 'Inactive']
 ['23-10-2017' '3158' 'Neutral' '99' '5' 'Inactive']
 ['24-10-2017' '4383' 'Neutral' '143' '4' 'Inactive']
 ['25-10-2017' '3881' 'Neutral' '125' '5' 'Inactive'

/tmp/ipython-input-3911660168.py:1: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  data = np.loadtxt("fit.txt",dtype = "str")


In [25]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [26]:
step_count = data[:, 1].astype(int)
mood = data[:, 2]
calories = data[:, 3].astype(int)
sleep = data[:, 4].astype(int)
activity = data[:, 5]

In [27]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [28]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [28]:
step_count
mood
calories
sleep
activity

#Question 4: What is the average step count on "Active" days?

In [33]:
np.mean(step_count[activity=='Active'])

np.float64(3226.5714285714284)

In [29]:
activity

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

In [ ]:
activity == "Active"

array([False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False, False,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False,  True, False,  True])

In [ ]:
step_count[activity == "Active"]

array([6915, 4732, 4550,  539, 6314,  614, 3149, 4005, 4880, 4136,  705,
        570,  269,  493,  995, 1163, 6676, 3608,  774, 1421, 4064, 2725,
       5934, 1867, 3721, 2909, 1648, 7102, 3941, 7422,  437, 1231, 4921,
        221, 6500, 3575, 5537, 4108, 5376, 3066,  500, 2203])

In [ ]:
np.mean(step_count[activity == "Active"])

np.float64(3226.5714285714284)

In [ ]:
step_count
mood
calories
sleep
activity

Question 5: How many days had more than 5000 steps and burned more than 150 calories?

In [38]:
((step_count>5000)&(calories>150)).sum()

np.int64(17)

In [ ]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [ ]:
calories

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [ ]:
(step_count > 5000) & (calories>150)

array([ True,  True, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True,  True, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
# True #1
# False # 0
True + True +False

2

In [ ]:
int(True)

1

In [ ]:
np.sum([True,False,True])

np.int64(2)

In [ ]:
np.sum((step_count > 5000) & (calories>150))

np.int64(17)

In [ ]:
step_count
mood
calories
sleep
activity

Question 6: What percentage of days had a "Sad" mood?
Options:

A. 80
B. 50
C. 30
D. 10

In [42]:
len(mood[mood=='Sad'])/len(mood)

0.3020833333333333

In [ ]:
np.sum(mood == 'Sad') /len(mood)

np.float64(0.3020833333333333)

In [ ]:
(np.sum(mood == 'Sad') /len(mood))  * 100

np.float64(30.208333333333332)

In [ ]:
step_count
mood
calories
sleep
activity

Question 7: What is the maximum number of steps taken on days with less than 6 hours of sleep?
Options:

A. 7422
B. 6500
C. 8000
D. 5642

In [44]:
np.max(step_count[sleep<6])

np.int64(7422)

In [ ]:
step_count[sleep<6]

array([5464,   25, 5461, 6915,   61, 4687, 1580, 3158, 4383, 3881,  292,
       2209, 4435, 4779, 1831, 2255,  539, 5464, 6041, 4068, 4033,  614,
       3149, 4880, 4136,  570, 4275, 4421, 5195, 3608, 3721, 2374, 2909,
       1648,  799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500,
       3575, 4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,
        299, 1447, 2599,  702,  133,  500, 2127, 2203])

In [ ]:
np.max(step_count[sleep<6])

np.int64(7422)

In [ ]:
step_count
mood
calories
sleep
activity

Question 8: What are the average calories burned per hour of sleep on "Inactive" days?
Options:

A. 18.62
B. 15.98
C. 23.78
D. 11.24

In [52]:
np.mean((calories[activity=='Inactive'])/(sleep[activity=='Inactive']))

np.float64(18.62282480893592)

In [48]:
np.sum(sleep[activity=='Inactive'])

np.int64(272)

In [ ]:
sleep[activity == 'Inactive']

array([5, 8, 5, 4, 6, 6, 7, 5, 6, 8, 5, 7, 5, 6, 8, 5, 4, 5, 6, 8, 5, 6,
       5, 5, 4, 5, 4, 4, 3, 2, 9, 5, 5, 6, 5, 6, 5, 6, 4, 4, 4, 5, 5, 4,
       3, 5, 3, 3, 3, 2, 3, 2, 8, 5])

In [ ]:
calories[activity == 'Inactive']

array([181, 197,   0, 174, 149, 140,  38,   1,  40, 101, 152, 113,  49,
        86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 141, 156,  57,
        72, 181, 197, 131, 154, 137, 145, 192, 146, 234, 167,  16,  76,
        25,  55, 129,  21,  28,  16,   5,   1,  10,  47,  84,  23,   4,
         0,   0])

In [ ]:
calories[activity == 'Inactive'] / sleep[activity == 'Inactive']


array([36.2       , 24.625     ,  0.        , 43.5       , 24.83333333,
       23.33333333,  5.42857143,  0.2       ,  6.66666667, 12.625     ,
       30.4       , 16.14285714,  9.8       , 14.33333333,  0.75      ,
       19.8       , 35.75      , 25.        , 21.5       ,  0.75      ,
        1.8       ,  1.66666667, 14.4       , 28.2       , 39.        ,
       11.4       , 18.        , 45.25      , 65.66666667, 65.5       ,
       17.11111111, 27.4       , 29.        , 32.        , 29.2       ,
       39.        , 33.4       ,  2.66666667, 19.        ,  6.25      ,
       13.75      , 25.8       ,  4.2       ,  7.        ,  5.33333333,
        1.        ,  0.33333333,  3.33333333, 15.66666667, 42.        ,
        7.66666667,  2.        ,  0.        ,  0.        ])

In [ ]:
np.mean(calories[activity == 'Inactive'] / sleep[activity == 'Inactive']
)

np.float64(18.62282480893592)

In [ ]:
step_count
mood
calories
sleep
activity

Question 9: Which mood had the highest average step count?


In [55]:
mood[np.where(step_count ==np.max(step_count))]

array(['Happy'], dtype='<U10')

Question 10: Calculate the correlation between step count and calories burned.


In [57]:
np.corrcoef(step_count,calories)[0,1]

np.float64(0.9892596952985985)

In [ ]:
step_count
mood
calories
sleep
activity

Question 11: On how many days was the mood "Sad" and sleep less than the median sleep? choose the correct snippet from thr below options
Options:

A. np.sum((mood == 'Sad') & (sleep < np.median(sleep)))
B. np.mean((mood == 'Sad') & (sleep <= np.median(sleep)))
C. len((mood == 'Sad') & (sleep < np.median(sleep)))
D. np.count_nonzero((sleep < mood) & 'Sad')

In [59]:
np.sum((mood=='Sad')&(sleep<np.median(sleep)))

np.int64(10)

In [ ]:
step_count
mood
calories
sleep
activity

Question 12: What is the standard deviation of step count only for "Happy" mood days?
Options:

A. 2088.40
B. 3081.60
C. 2085.90
D. 1008.90

In [61]:
np.std(step_count[mood=='Happy'])

np.float64(2088.4016254961593)

Question 13: What is the most frequent number of hours slept?
Options:

A. 5
B. 3
C. 10
D. 7

In [65]:
import scipy.stats as st

In [66]:
st.mode(sleep)

ModeResult(mode=np.int64(5), count=np.int64(37))

In [ ]:
step_count
mood
calories
sleep
activity

Question 14: Which mood has the lowest average calories burned on days with more than the median hours of sleep and a step count above 4000?
Options:

A) 'Sad'
B) 'Neutral'
C) 'Happy'
D) 'Cannot be determined'

In [72]:
mood[(sleep>np.median(sleep))& (step_count>4000)]

array(['Sad', 'Sad', 'Sad', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Sad', 'Happy', 'Happy'], dtype='<U10')

In [75]:
new = calories[(sleep>np.median(sleep))& (step_count>4000)]
new

array([197, 149, 140, 150, 129, 150, 154, 193, 139, 192, 234, 220, 131,
       194])

In [78]:
# Sad
np.mean(new[mood[(sleep>np.median(sleep))& (step_count>4000)]=='Sad'])

np.float64(176.5)

In [79]:
# Happy
np.mean(new[mood[(sleep>np.median(sleep))& (step_count>4000)]=='Happy'])

np.float64(170.77777777777777)

In [80]:
# Neutral
np.mean(new[mood[(sleep>np.median(sleep))& (step_count>4000)]=='Neutral'])

np.float64(129.0)

In [ ]:
step_count
mood
calories
sleep
activity

Question 15: What is the longest streak (in days) where 'Inactive' days had calories burned less than the daily mean across the full dataset?
Options:

A) 2
B) 8
C) 4
D) 1

In [81]:
np.mean(calories)

np.float64(93.44791666666667)

In [83]:
cal = calories[activity=='Inactive']
cal

array([181, 197,   0, 174, 149, 140,  38,   1,  40, 101, 152, 113,  49,
        86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 141, 156,  57,
        72, 181, 197, 131, 154, 137, 145, 192, 146, 234, 167,  16,  76,
        25,  55, 129,  21,  28,  16,   5,   1,  10,  47,  84,  23,   4,
         0,   0])

In [85]:
np.where(cal<np.mean(calories))

(array([ 2,  6,  7,  8, 12, 13, 14, 19, 20, 21, 22, 25, 26, 37, 38, 39, 40,
        42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53]),)

42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53

12 consecutive